config/routes.rb
Rails.application.routes.draw do
  



  resources :users do
    resources :firms
  end
  
  root 'static_pages#home'
  get     'contact' => 'static_pages#contact'
  get     'about'   => 'static_pages#about'
  get     'how'     => 'static_pages#how'
  get     'signup'  => 'users#new'
  get     'login'   => 'static_pages#home'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'
end

app/models/firm.rb
class Firm < ActiveRecord::Base
  belongs_to :user
  belongs_to :asesor, class_name: 'User'
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :legal, presence: true, uniqueness: { case_sensitive: false }
  validates :employees, presence: true
  validates :sales, presence: true
  validate :asesor_must_be_admin
  
  def asesor_must_be_admin
    errors.add(:asesor, "Asesor tiene que ser admin") if asesor && !asesor.admin
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  
  
  scope :admins, ->  { where(admin: true) }
  before_save { self.email = email.downcase }
  has_many :firms
  has_many :asesoradas, class_name: "Firm", foreign_key: "asesor_id"
  
  EMAIL_REGEXP = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,  presence: { message: "no puede estar vacío" }, length: { maximum: 50  }
  validates :email, presence: { message: "no puede estar vacío" }, length: { maximum: 255 },
                    format:     { with: EMAIL_REGEXP },
                    uniqueness: { case_sensitive: false, message: "ya está en uso." }
  validates :password, presence: { message: "no puede estar vacío" }, 
                       length:   { minimum: 6, message: "debe tener 6 caracteres o más"},
                       allow_nil: true
        
  has_secure_password      
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper
  private
  
    def require_login
      unless logged_in?
        store_location
        flash[:danger] = "Por favor inicie sesión"
        redirect_to root_url
      end
    end
    
    def require_correct_user
      @user = User.find(params[:user_id] || params[:id])
      redirect_to root_url unless current_user?(@user)
    end
    
    def require_admin
      redirect_to root_url unless current_user.admin?
    end
    
    def require_correct_user_or_admin
      @user = User.find(params[:user_id] || params[:id])
      redirect_to root_url unless current_user.admin? || current_user?(@user)
    end
    
end

app/controllers/firms_controller.rb
class FirmsController < ApplicationController
  
  before_action :require_login
  before_action :require_correct_user_or_admin

  def index
    if current_user.admin?
      @firms  = Firm.all.paginate(page: params[:page_id])
    else 
      @firms = current_user.firms.paginate(page: params[:page_id])
    end
  end

  def show
    @firm = Firm.find(params[:id])
  end

  def new
    @user = current_user
    @firm = @user.firms.new
  end

  def create
    @firm = current_user.firms.build(firm_params)
    if @firm.save
      # handle success
      flash[:success] = "Empresa registrada"
      redirect_to user_firm_path(id: @firm.id, user_id: @user.id)
    else
      render 'new'
    end
  end

  def edit
    @firm = Firm.find(params[:id])
  end

  def update
    @firm = Firm.find(params[:id])
    if !current_user.admin? && firm_params.include?(:asesor_id)
      redirect_to root_path
    elsif @firm.update_attributes(firm_params)
      flash[:success] = "Información Actualizada"
      redirect_to user_firm_path(user_id: current_user, id: @firm.id)
    else
      render 'edit'
    end
  end

  def destroy
    @firm = Firm.find(params[:id])
    @firm.destroy
    flash[:success] = "Empresa Eliminada"
    redirect_to root_url
  end
  
  private 
  
    def firm_params
      params.require(:firm).permit(:name, :legal, :employees, :sales, :industry, :asesor_id)
    end
  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
    else
      flash[:danger] = "Correo/Contraseña inválidos"
      redirect_to root_path
    end
  end
  
  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    redirect_to current_user if current_user
  end

  def contact
  end

  def about
  end
  
  def how
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :require_login, only: [:index, :show, :edit, :update]
  before_action :require_admin, only: [:index, :destroy]
  before_action :require_correct_user_or_admin,  only: [:edit, :update]
  
  def index
    @users = User.paginate(page: params[:page]).per_page(10)
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Bienvenido a PACPYMES, por favor registre a su empresa.'
      redirect_to @user
    else
      render 'new'
    end
  end
  
  
  def edit 
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # handle success
      flash[:success] = "Información Actualizada"
      redirect_to @user
    else
      #handle failure
      render 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    if @user != current_user
      @user.destroy
      flash[:success] = "Usuario Eliminado"
      redirect_to users_url
    else
      redirect_to root_url
    end
  end
  
  
  private
  
    def user_params
      if current_user && current_user.admin?
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
      else
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title='')
    base_title = "PACPYMES"
    if title.blank?
      base_title
    else
      "#{title} | #{base_title}"
    end
  end
  
  
  def detalles_icon
    content_tag(:span, "", class: "glyphicon glyphicon-zoom-in", title: "Detalles")
  end
  
  def editar_icon
    content_tag(:span, "", class: "glyphicon glyphicon-pencil", title: "Editar")
  end
  
  def admin_icon(user)
    if user.admin?
      content_tag :span, "", class: "glyphicon glyphicon-ok"
    else
      content_tag :span, "", class: "glyphicon glyphicon-remove"
    end
  end
  
  def borrar_icon
    content_tag(:span, "", class: "glyphicon glyphicon-trash", title: "Eliminar")
  end
end

app/helpers/firms_helper.rb
module FirmsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end
  
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  

    
end

app/views/firms/_firm.html.erb
<tr>
  <td><%= "#{firm.name} (#{firm.legal})" %></td>
  <td><%= link_to firm.user.name, firm.user %></td>
  <td></td>
  <td><%= link_to(firm.asesor.name, firm.asesor) if firm.asesor %></td>
  <td>
    <%= link_to detalles_icon, user_firm_path(user_id: firm.user, id: firm) %>
    <%= link_to editar_icon, edit_user_firm_path(user_id: firm.user, id: firm) %>
    <%= link_to borrar_icon, user_firm_path(user_id: firm.user, id: firm), method: :delete, data: { confirm: "sure?" } %>
  </td>
  
</tr>

app/views/firms/_form.html.erb
<%= form_for([@user, @firm], :html => {:class => 'form-horizontal'}) do |f| %>
  <div class="form-group">
    <%= f.label :name, "Nombre", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :legal, "Razón Social", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :legal, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :legal, "Facturación", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :sales, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :employees, "Empleados", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :employees, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :industry, "Sector", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :industry, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :asesor, "Asesor", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <% if current_user.admin? %>
        <%= f.select :asesor_id, User.admins.collect { |a| [ a.name, a.id ] }, {include_blank: true}, { class: "form-control"} %>
      <% else %>
        <%= f.text_field :asesor, class: "form-control", disabled: true %>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <% if @firm.new_record? %>
        <%= f.submit "Crear Empresa", class: "btn btn-primary" %>
      <% else %>
         <%= f.submit "Actualizar", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

<% end %>

app/views/firms/destroy.html.erb
<h1>Firms#destroy</h1>
<p>Find me in app/views/firms/destroy.html.erb</p>

app/views/firms/edit.html.erb
<%= provide(:title, "Editar Empresa") %>
<div class="container">
  <legend>Editar empresa</legend>
  <%= render 'shared/errors', object: @firm %>
  <%= render 'form' %>
  
</div>

app/views/firms/index.html.erb
<% provide(:title, "Empresas") %>
<div class="container">

  <legend>Empresas (<%= @firms.count %>)</legend>
  <%= will_paginate :previous_label => 'Anterior', :next_label => 'Siguiente' %>
  <table class="table table-condensed">
    <tr>
      <td>Nombre</td>
      <td>Usuario</td>
      <td>Departamento</td>
      <td>Asesor</td>
      <td>Acciones</td>
    </tr>
    <%= render @firms %>
  </table>
</div>

app/views/firms/new.html.erb
<div class="container">
  <legend>Registrar Empresa</legend>
  <%= render 'shared/errors', object: @firm %>
  <%= render 'form' %>
</div>

app/views/firms/show.html.erb
<article class="movie">
<h1><%= @firm.name %> </h1>
<p>
  <h2>Sector: <%= @firm.industry %></h2>
</p>
<p>
  <h2>Empleados: <%= @firm.employees %></h2>
</p>
</article>

app/views/firms/update.html.erb
<h1>Firms#update</h1>
<p>Find me in app/views/firms/update.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
  <small> PACPYMES - Programa de Apoyo a la Competitividad de las Pequeñas y Medianas Empresas</small>
  <nav>
    <ul>
      <li><%= link_to "Inicio",          root_path    %></li>
      <li><%= link_to "¿Qué es?",        about_path   %></li>
      <li><%= link_to "¿Cómo funciona?", how_path     %></li>
      <li><%= link_to "Contacto",        contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "PACPYMES", root_path, class: "navbar-brand" %>
        
      </div>
      <%  if logged_in? %>
      
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user.admin? %>
              <li><%= link_to "Usuarios", users_path %></li>
            <% end %>
            <li><%= link_to "Empresas", user_firms_path(user_id: current_user) %></li>
            <li><a href="#">Proyectos</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mi Cuenta <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Perfil", current_user %></li>
                <li><%= link_to "Configuración", edit_user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to  "Cerrar Sesión", logout_path, method: :delete %></a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
        
      <% else %>
      
       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
         <%= form_for(:session, url: login_path, :html => { :class => 'navbar-form navbar-right'}) do |f| %>
           <div class="form-group">
             <%= f.email_field :email, placeholder: "Correo", class: "form-control" %>
           </div>
           <div class="form-group">
             <%= f.password_field :password, placeholder: "Contraseña", class: "form-control" %>
           </div>
            <button type="submit" class="btn btn-default">Iniciar Sesión</button>
         <% end %>
        </div>
        
      <% end %>
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.png' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container" id="wrapper">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
  </div>
  <div class="container">
    <%= render 'layouts/footer' %>
  </div>


</body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      El formulario tiene <%= pluralize(object.errors.count, 'error') %>
    </div>
      <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<%= provide(:title, "¿Qué es?") %>
<h1>¿Qué es PACPYMES?</h1>
<p>Es un programa de cooperación internacional para apoyar la competitividad de las Pequeñas y Medianas Empresas</p>

app/views/static_pages/contact.html.erb
<%= provide(:title, "Contacto") %>
<h1>Contacto</h1>
<p>pacpymes@pacpymes.com</p>

app/views/static_pages/home.html.erb
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <h1>PACPYMES</h1>
            <p>Programa de Apoyo a la Competitividad de las Pequeñas y Medianas Empresas</p>
             <p><%= link_to "Registrarse >>", signup_path, class: "btn btn-primary btn-lg" %></p>
          </div>
          <div class="col-md-4"><%= image_tag "pacpymes.jpg", id: "logo" %></div>
        
        </div>
        
       
        
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>¿Qué es?</h2>
          <p>Es un programa de cooperación internacional que apoya a las PYMES uruguayas con fondos para que contraten asistencia técnica. </p>
          <p><%= link_to "Leer Más >>", about_path, class: "btn btn-default" %></p>
        </div>
        <div class="col-md-6">
          <h2>¿Cómo funciona?</h2>
          <p>Para participar del programa, debe crear un usuario <%= link_to "aquí", signup_path %> y registrar su empresa. Luego, le asignaremos un asesor que realizará un diagnóstico del funcionamiento de su empresa para determinar cuáles son las áreas en las que debe recibie apoyo de un consultor.</p>
          <p><%= link_to "Leer Más >>", how_path, class: "btn btn-default" %></p>
       </div>
      </div>
    </div>

app/views/static_pages/how.html.erb
<%= provide(:title, "¿Cómo funciona?") %>
<h1>¿Cómo funciona?</h1>
<p>Cree un usuario y registre su empresa!</p>

app/views/users/_form.html.erb
<%= form_for @user, :html => {:class => 'form-horizontal'}  do |f| %>
  <div class="form-group">
    <%= f.label :name, "Nombre", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :email, "Correo" , class: "col-sm-2 control-label"%>
    <div class="col-sm-4">
      <%= f.email_field :email, class: "form-control" %>
    </div>
  </div>
  <% if current_user && current_user.admin? %>
    <div class="form-group">
      <%= f.label :admin, "Admin" , class: "col-sm-2 control-label"%>
      <div class="col-sm-4">
        <%= f.check_box :admin, class: "form-control" %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :password, "Contraseña", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, "Confirmar Contraseña", class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <% if @user.new_record? %>
        <%= f.submit "Registrarse", class: "btn btn-primary" %>
      <% else %>
         <%= f.submit "Actualizar", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= admin_icon(user) %></td>
  <td>
    <%= link_to detalles_icon, user %>
    <%= link_to editar_icon,   edit_user_path(user) %>
    <%= link_to borrar_icon,   user, method: :delete, data: { confirm: "¿Seguro?" } %> 
  </td>
</tr>

app/views/users/edit.html.erb
<%= provide(:title, "Editar Cuenta") %>
<div class="container">
  <legend>Editar cuenta</legend>
  <%= render 'shared/errors', object: @user %>
  <%= render 'form' %>
  
</div>

app/views/users/index.html.erb
<% provide(:title, "Usuarios") %>
<div class="container">
  <div class="col-md-9" id="tabla">
    <legend>Usuarios (<%= User.count %>)</legend>
    <%= will_paginate :previous_label => 'Anterior', :next_label => 'Siguiente' %>
    <table class="table table-condensed">
      <tr>
        <th>Nombre</th>
        <th>Correo</th>
        <th>Admin?</th>
        <th>Acciones</th>
      </tr>
        <%= render @users %>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<%= provide(:title, "Registrarse") %>
<div class="container">
  <legend>Registrarse</legend>
  <%= render 'shared/errors', object: @user %>
  <%= render 'form' %>
  
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row"> 
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %> <%= content_tag(:small, "(Admin)") if @user.admin? %>
      </h1>
      <p><%= @user.email %></p>
      <% unless @user.admin? %>
        <p><%= link_to "Registrar Empresa",  new_user_firm_path(@user), class: "btn btn-primary" %></p>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <section class="firms">
      <table class="table table-condensed">
    <tr>
      <td>Nombre</td>
      <td>Usuario</td>
      <td>Departamento</td>
      <td>Asesor</td>
      <td>Acciones</td>
    </tr>
    <% if @user.admin? %>
      <%= render @user.asesoradas %>
    <% else %>
      <%= render @user.firms %>
    <% end %>
  </table>
    </section>
  </div>
</div>